#### From the IBL database, get data on weight and trial counts under different water regimes at CSHL
Anne Urai, CSHL, 2019

In [1]:
# PYTHON STARTS BY IMPORTING 'MODULES' AND 'PACKAGES' THAT WE'LL USE LATER

# GENERAL THINGS FOR COMPUTING AND PLOTTING
import pandas as pd
import numpy as np
import os, sys, time

# visualisation
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="darkgrid", context="paper")

# set a path where you want figures to be saved
figpath  = os.path.join(os.path.expanduser('~'), 'Data/Figures_IBL')

# ibl specific things
import datajoint as dj
from ibl_pipeline import reference, subject, action, acquisition, data, behavior

Connecting anneurai@datajoint.internationalbrainlab.org:3306

If your login to DataJoint was successful, you should see something like 

'Connecting youruser@datajoint.internationalbrainlab.org:3306'

In [2]:
# FIND THE DATA WE NEED
# FIRST, WHICH SUBJECTS ARE DOING THIS CA EXPERIMENT?
subj = (subject.Subject() - subject.Death & 'subject_birth_date < "2018-09-01"').proj('subject_nickname', 'sex') * \
    (subject.SubjectLab() & 'lab_name="churchlandlab"').proj()
print(subj)

*subject_uuid  subject_nickna sex
+------------+ +------------+ +-----+
1208c089-8b8e- IBL_13         M
3e97e1d3-2a0f- IBL_34         M
3f854f88-7879- IBL_11         M
52a800fc-cbbc- IBL_1          M
55381f61-4e47- IBL_46         M
7c751b49-55a6- IBL_10         M
 (Total: 6)

In [8]:
# get date for each weighing
weight_with_date = action.Weighing.proj('weight', session_date='DATE(weighing_time)')
# create a table with primary key to be the combination of subject_uuid and session_date
# dj.U, U means uniform, all possible combinations of subject uuid and session_date, when
# restricted with weight_with_date, it returns all existing combinations of subject_uuid and 
# session_date in the table weight_with_date
# Note that there are more entries in weight_with_date than in weight_date, indicating there
# exists more than one weighing for some dates.
weight_date = (dj.U('subject_uuid', 'session_date') & weight_with_date)

# Aggregation to get average weight for each date
# before .aggr is the table you want aggregate, basically you get one value for each entry in 
# weight_with_date
# first argument is the table that is useful to compute the value you need, here weight_with_date
# provides all weights for each date, 'weight' is an attribute in the table weight_with_date
# note that the results have the same number of entries as weight_date
avg_weight_date = weight_date.aggr(weight_with_date, avg_weight='AVG(weight)')

# NOW DO THE SAME FOR WATER
water_with_date = action.WaterAdministration.proj('watertype_name', 'water_administered', 
                                                  session_date='DATE(administration_time)')
water_date = (dj.U('subject_uuid', 'session_date') & water_with_date)
total_water_date = water_date.aggr(water_with_date, total_water='SUM(water_administered)', 
                                   watertype="CONCAT_WS('; ', watertype_name)")

# get session with date
session_with_date = behavior.TrialSet.proj('n_trials') \
    * (acquisition.Session.proj(session_date='DATE(session_start_time)') & 'session_date > "2019-05-01"')
# Now you can join (*) the two tables avg_weight_date and session_with_date.
# Join * will automatically find matched session_date in both tables, and only show entries where
# these dates exist in both tables. Note there are fewer entries in this resulting table, because
# on some dates weight is missing and other dates session is missing
b = subj * session_with_date * avg_weight_date * total_water_date
b

*subject_uuid  *session_start *session_date  subject_nickna sex     n_trials     avg_weight     total_water    watertype
+------------+ +------------+ +------------+ +------------+ +-----+ +----------+ +------------+ +------------+ +------------+
1208c089-8b8e- 2019-05-02 11: 2019-05-02     IBL_13         M       398          23.72999954223 0.944999992847 Water 10% Sucr
1208c089-8b8e- 2019-05-03 11: 2019-05-03     IBL_13         M       535          23.27000045776 1.302000045776 Water 10% Sucr
1208c089-8b8e- 2019-05-06 11: 2019-05-06     IBL_13         M       192          26.06999969482 0.432000011205 Water
1208c089-8b8e- 2019-05-07 11: 2019-05-07     IBL_13         M       104          25.70000076293 0.167999997735 Water
3e97e1d3-2a0f- 2019-05-02 15: 2019-05-02     IBL_34         M       802          23.48999977111 2.019000053405 Water 10% Sucr
3e97e1d3-2a0f- 2019-05-03 15: 2019-05-03     IBL_34         M       792          24.01000022888 2.033999919891 Water 10% Sucr
3e97e1d3-2a0f- 2019-05-06 14: 2019-05-06     IBL_34         M       175          26.77000045776 0.398999989032 Water 10% Sucr
3e97e1d3-2a0f- 2019-05-07 15: 2019-05-07     IBL_34         M       215          26.82999992370 0.515999972820 Water
3f854f88-7879- 2019-05-02 16: 2019-05-02     IBL_11         M       426          26.61000061035 0.950999975204 Water 10% Sucr
3f854f88-7879- 2019-05-03 14: 2019-05-03     IBL_11         M       368          27.04000091552 0.960000038146 Water
3f854f88-7879- 2019-05-06 16: 2019-05-06     IBL_11         M       156          31.12999916076 0.254999995231 Water 10% Sucr
3f854f88-7879- 2019-05-07 16: 2019-05-07     IBL_11         M       106          31.52000045776 0.162000000476 Water
   ...
 (Total: 24)

In [ ]:
df = pd.DataFrame(b.fetch(as_dict=True))

In [7]:
df['watertype'].unique()

array(['Water 10% Sucrose', 'Water 2% Citric Acid', 'Water'], dtype=object)